package aman_car_showroom;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Aman Kumar Jha
 */

public class bill extends javax.swing.JFrame {
    
    Connection con=null;
    Statement stmt=null;
    public bill() {
        
        
    }
     public bill(String invoice,String name,String brand,String model,String gear,String price,String color,String contact,int grandtot,String vins) {
         
         initComponents();
         
         invoicenumber.setText(invoice);
         vat_invoice.setText("13"); 
         name_invoice.setText(name);
         brand_invoice.setText(brand);
         model_invoice.setText(model);
         gear_invoice.setText(gear);
         price_invoice.setText(price);
         color_invoice.setText(color);
         contact_invoice.setText(contact);
         grand_total.setText(Integer.toString((int)grandtot));
        vin.setText(vins);
        
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        goback = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        name_invoice = new javax.swing.JTextField();
        brand_invoice = new javax.swing.JTextField();
        gear_invoice = new javax.swing.JTextField();
        price_invoice = new javax.swing.JTextField();
        vat_invoice = new javax.swing.JTextField();
        grand_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contact_invoice = new javax.swing.JTextField();
        model_invoice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        invoicenumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        color_invoice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMAN ENTERPRISE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 447, 31));

        goback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        goback.setText("<<");
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 23, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel2.setText("NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel3.setText("BRAND:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel4.setText("MODEL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 29));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setText("GEAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, 33));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("PRICE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("VAT (%):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 140, 29));

        grandtotal.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        grandtotal.setText("GRAND TOTAL:");
        getContentPane().add(grandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 140, 31));
        getContentPane().add(name_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 330, 30));
        getContentPane().add(brand_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 330, 30));
        getContentPane().add(gear_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 330, 30));

        price_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_invoiceActionPerformed(evt);
            }
        });
        getContentPane().add(price_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 330, 30));
        getContentPane().add(vat_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 334, 30));
        getContentPane().add(grand_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 330, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.blue);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INVOICE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 270, 20));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel10.setText("CONTACT :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));
        getContentPane().add(contact_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 330, 30));
        getContentPane().add(model_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 330, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel8.setText("INVOICE NUMBER:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 140, 30));
        getContentPane().add(invoicenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 330, 30));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel11.setText("COLOR:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, 30));
        getContentPane().add(color_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 330, 30));

        jLabel12.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 760, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel13.setText("VIN:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 40, -1));

        vin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinActionPerformed(evt);
            }
        });
        getContentPane().add(vin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        // TODO add your handling code here:
        frontpage obj=new frontpage();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_gobackMouseClicked

    private void price_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_invoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_invoiceActionPerformed

    private void vinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand_invoice;
    private javax.swing.JTextField color_invoice;
    private javax.swing.JTextField contact_invoice;
    private javax.swing.JTextField gear_invoice;
    private javax.swing.JToggleButton goback;
    private javax.swing.JTextField grand_total;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JTextField invoicenumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField model_invoice;
    private javax.swing.JTextField name_invoice;
    private javax.swing.JTextField price_invoice;
    private javax.swing.JTextField vat_invoice;
    private javax.swing.JTextField vin;
    // End of variables declaration//GEN-END:variables
}
