package aman_car_showroom;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
import java.util.Arrays;
import java.util.*;  
/**
 *
 * @author Aman Kumar Jha
 */
public class frontpage extends javax.swing.JFrame {
Connection con=null;
Statement stmt=null;
Connection stmtt=null;
ResultSet rs=null;
PreparedStatement ps=null;
    /**
     * Creates new form frontpage
     */
    //String namee,brands,models,gears,pr;
        int []pricee=new int[10];
        HashMap<String,Integer> hm=new HashMap<String,Integer>();
        String []carmodel=new String[10];
    public frontpage() {
        
        //initComponents();
        
            carmodel[0]="HatchBack-S-Class";
            carmodel[1]="HatchBack-E-Class";
            carmodel[2]="HatchBack-A-Class";
            carmodel[3]="Sedan-E-Class";
            carmodel[4]="MPV-S-Class";
            carmodel[5]="SUV-E-Class";
            carmodel[6]="SUV-A-Class";
            carmodel[7]="Crossover";
            carmodel[8]="Coupe";
            carmodel[9]="Convertible";
        for(int i=0;i<10;i++)
        {
            pricee[i]=500000+(i+11)*19;
        }
         
        
        for(int i=0;i<10;i++)
        {  
          hm.put(carmodel[i],pricee[i]);
        }  
        
        String url="url:oracle:thin:@localhost:1521:XE";
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                System.out.println("Driver loaded\n");
                con=DriverManager.getConnection(url,"system","aman");
            }
            catch(ClassNotFoundException e)
            {
                System.out.println("driver not found\n");
            }
            catch(SQLException e)
            {
                System.out.println("Connection not establish");
            }
            if(con!=null)
            {
                System.out.println("Connection Established\n");
                
               initComponents();
              //vint.setText();
               
               fetch();
            }   
        
    }
    private void fetch()
        {
            try
            {
                
                String str="select * from bill";
                ps=con.prepareStatement(str);
                rs=ps.executeQuery(str);
                tab.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Unable to Display Table!!!",
            "Error",JOptionPane.ERROR_MESSAGE);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        brand = new javax.swing.JComboBox<>();
        model = new javax.swing.JComboBox<>();
        gear = new javax.swing.JComboBox<>();
        price = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        color = new javax.swing.JComboBox<>();
        booknow = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        contacts = new javax.swing.JTextField();
        vin = new javax.swing.JLabel();
        vint = new javax.swing.JTextField();
        vintbutton = new javax.swing.JToggleButton();
        jLabel21 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name_ser = new javax.swing.JTextField();
        cost_ser = new javax.swing.JTextField();
        brand_ser = new javax.swing.JComboBox<>();
        model_ser = new javax.swing.JComboBox<>();
        pay = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        colors = new javax.swing.JComboBox<>();
        con_ser = new javax.swing.JTextField();
        contact_ser = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        gear_ser = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        search_invoice = new javax.swing.JTextField();
        getdetail = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        search_emp = new javax.swing.JTextField();
        search = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        tot_sale = new javax.swing.JToggleButton();
        totsale = new javax.swing.JTextField();
        top_sales = new javax.swing.JToggleButton();
        convert_sale = new javax.swing.JToggleButton();
        convertible = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        brand1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        booknow1 = new javax.swing.JToggleButton();
        jLabel26 = new javax.swing.JLabel();
        vin1 = new javax.swing.JLabel();
        gear1 = new javax.swing.JComboBox<>();
        vint1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        contacts1 = new javax.swing.JTextField();
        color1 = new javax.swing.JComboBox<>();
        model1 = new javax.swing.JComboBox<>();
        vintbutton1 = new javax.swing.JToggleButton();
        no_car = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMAN ENTERPRISE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 350, 30));

        logout.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        logout.setText("LogOut");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel2.setText("CUSTOMER NAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel3.setText("BRAND:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("MODEL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setText("GEAR:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("PRICE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 250, 30));

        brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "BMW", "Buggati", "General Motor", "Tata", "Audi", "Renault", "Ferrai", "Mercedes", "Volks-Vagon", "Chevrolet", "Jaguar" }));
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        jPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, -1));

        model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "HatchBack-S-Class", "HatchBack-E-Class", "HatchBack-A-Class", "Sedan-E-Class", "MPV-S-Class", "SUV-E-Class", "SUV-A-Class", "Crossover", "Coupe", "Convertible" }));
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, -1));

        gear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "5", "6" }));
        jPanel1.add(gear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, -1));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 250, 30));

        jLabel15.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel15.setText("COLOR:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, -1));

        color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Red", "Black", "White", "Gray", "Silver", " " }));
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 160, -1));

        booknow.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        booknow.setText("BOOK NOW");
        booknow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booknowMouseClicked(evt);
            }
        });
        jPanel1.add(booknow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel17.setText("CONTACT NUMBER:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 30));
        jPanel1.add(contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 250, 30));

        vin.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        vin.setText("VIN:");
        jPanel1.add(vin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 20));
        jPanel1.add(vint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 250, 30));

        vintbutton.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        vintbutton.setText("GET VIN");
        vintbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vintbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(vintbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel21.setText("GENDER:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 110, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 20));

        jLabel22.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel22.setText("SALARY:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 20));
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 250, 30));

        jTabbedPane1.addTab("DEALER", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("CUSTOMER NAME:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel8.setText("BRAND:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel9.setText("MODEL:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel11.setText("PRICE:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        name_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_serActionPerformed(evt);
            }
        });
        jPanel2.add(name_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 250, 30));
        jPanel2.add(cost_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 260, 30));

        brand_ser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "BMW", "Buggati", "General Motor", "Tata", "Audi", "Renault", "Ferrai", "Mercedes", "Volks-Vagon", "Chevrolet", "Jaguar" }));
        jPanel2.add(brand_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 160, -1));

        model_ser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "HatchBack-S-Class", "HatchBack-E-Class", "HatchBack-A-Class", "Sedan-E-Class", "MPV-S-Class", "SUV-E-Class", "SUV-A-Class", "Crossover", "Coupe", "Convertible" }));
        jPanel2.add(model_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 160, -1));

        pay.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        pay.setText("PAY");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        jPanel2.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 110, 40));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel16.setText("COLOR:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        colors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Black", "Blue", "Brown", "Gray", "Green", "Orange", "Red", "Voilet", "White", "Yellow", "DarkSlateGray", "Ghost White", "Off gray", "Brass", "CopperYellow", " " }));
        colors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsActionPerformed(evt);
            }
        });
        jPanel2.add(colors, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, -1));
        jPanel2.add(con_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 260, 30));

        contact_ser.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        contact_ser.setText("CONTACT:");
        jPanel2.add(contact_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 20));

        jLabel18.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel18.setText("GEAR:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 30));

        gear_ser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "5", "6" }));
        jPanel2.add(gear_ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, -1));

        jTabbedPane1.addTab("SERVICING:", jPanel2);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel13.setText("INVOICE NUMBER:");

        getdetail.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        getdetail.setText("GET DETAIL");
        getdetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getdetailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getdetail)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(search_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(getdetail)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CUSTOMER:", jPanel3);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel14.setText("EMPLOYEE ID:");

        search.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        search.setText("SEARCH");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(search_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(114, 114, 114))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(search)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EMPLOYEE:", jPanel4);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("SALES");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "invoice", "Name", "Brand", "Model", "Gear", "Price", "Contact", "GrandTotal", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        tot_sale.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        tot_sale.setText("TOTAL SALE:");
        tot_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tot_saleMouseClicked(evt);
            }
        });

        totsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totsaleActionPerformed(evt);
            }
        });

        top_sales.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        top_sales.setText("TOP SALES");
        top_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                top_salesMouseClicked(evt);
            }
        });

        convert_sale.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        convert_sale.setText("CONVERTIBLE SALES:");
        convert_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convert_saleMouseClicked(evt);
            }
        });

        convertible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 393, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(convert_sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(top_sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tot_sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totsale, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(convertible))
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totsale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tot_sale)))
                .addGap(18, 18, 18)
                .addComponent(top_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(convertible)
                    .addComponent(convert_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("SALES:", jPanel6);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel23.setText("DEALER NAME:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel5.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 250, 30));

        jLabel24.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel24.setText("BRAND:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        brand1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "BMW", "Buggati", "General Motor", "Tata", "Audi", "Renault", "Ferrai", "Mercedes", "Volks-Vagon", "Chevrolet", "Jaguar" }));
        brand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand1ActionPerformed(evt);
            }
        });
        jPanel5.add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, -1));

        jLabel25.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel25.setText("MODEL:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 30));

        booknow1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        booknow1.setText("BOOK NOW");
        booknow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booknow1MouseClicked(evt);
            }
        });
        jPanel5.add(booknow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel26.setText("CONTACT NUMBER:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 30));

        vin1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        vin1.setText("VIN:");
        jPanel5.add(vin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 20));

        gear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "5", "6" }));
        jPanel5.add(gear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, -1));
        jPanel5.add(vint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 250, 30));

        jLabel27.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel27.setText("COLOR:");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        jLabel28.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel28.setText("GEAR:");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 30));
        jPanel5.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 250, 30));

        jLabel29.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel29.setText("PRICE:");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 80, 30));

        contacts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacts1ActionPerformed(evt);
            }
        });
        jPanel5.add(contacts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 250, 30));

        color1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Red", "Black", "White", "Gray", "Silver", " " }));
        jPanel5.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 160, -1));

        model1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "HatchBack-S-Class", "HatchBack-E-Class", "HatchBack-A-Class", "Sedan-E-Class", "MPV-S-Class", "SUV-E-Class", "SUV-A-Class", "Crossover", "Coupe", "Convertible" }));
        jPanel5.add(model1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, -1));

        vintbutton1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        vintbutton1.setText("GET VIN");
        vintbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vintbutton1MouseClicked(evt);
            }
        });
        jPanel5.add(vintbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        no_car.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel5.add(no_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 160, -1));

        jLabel30.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel30.setText("NUMBER OF CARS:");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, 20));

        jTabbedPane1.addTab("MANUFRACTURER", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1190, 550));

        jLabel12.setText("________________________________________________________________________________________________________________________________________________________________________________________________________");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel19.setText("___________________________________________________________________________________________________________________________________________________________________________");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void name_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_serActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_serActionPerformed

    private void booknowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booknowMouseClicked
        // TODO add your handling code here:
        frontpage object=new frontpage();
        if(brand.getSelectedItem().toString().equals("Select...")||model.getSelectedItem().toString().equals("Select...")||
                gear.getSelectedItem().toString().equals("Select...")||color.getSelectedItem().toString().equals("Select...")||gender.getSelectedItem().toString().equals("Select..."))
        {
            JOptionPane.showMessageDialog(this,"Enter Valid Data...!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
            
                stmt=con.createStatement();
                //stmtt=con.createStatement();
                String namee=name.getText();
                String brande=brand.getSelectedItem().toString();
                String models=model.getSelectedItem().toString();
                String geare=gear.getSelectedItem().toString();
                String pricee=price.getText();
                String contacte=contacts.getText();
                String colore=color.getSelectedItem().toString();
                String sex=gender.getSelectedItem().toString();
                String sal=salary.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/ddHH:mm:ss");
                Date dt=new Date();
                String d=dateFormat.format(dt);
                String invoice = d.replaceAll("[-+.^:,/]","");
                String male="Male";
                String female="Female";
                //String set="M"+invoice;
                // vint.setText(set);
                //vint.setText(invoice+models);
                int grandtot=(Integer.parseInt(price.getText())*13)/100+Integer.parseInt(price.getText());
                String s="insert into bill values('"+invoice+"','"+namee+"','"+brande+"','"+models+"','"+geare+"','"+pricee+"','"+contacte+"','"+grandtot+"','"+colore+"','"+sex+"','"+sal+"')";
                stmt.executeUpdate(s);
                String str="insert into customer values('"+invoice+"','"+namee+"','"+sal+"','"+sex+"','"+models+"','"+brande+"','"+pricee+"')";
                stmt.executeUpdate(str);
                if(gender.getSelectedItem().toString().equalsIgnoreCase(male))
                {
                    System.out.println("amanmale\n");
                    String strr="insert into male_customer values('"+invoice+"','"+namee+"','"+sal+"','"+sex+"','"+models+"','"+brande+"','"+pricee+"')";
                    stmt.executeUpdate(strr);
                    
                }
                if(gender.getSelectedItem().toString().equalsIgnoreCase(female))
                {
                    System.out.println("aman\n");
                    String strn="insert into female_customer values('"+invoice+"','"+namee+"','"+sal+"','"+sex+"','"+models+"','"+brande+"','"+pricee+"')";
                    stmt.executeUpdate(strn);
                }
                System.out.println("Records inserted into the table...!!!");
                bill obj=new bill(invoice,name.getText(),brand.getSelectedItem().toString(),model.getSelectedItem().toString(),gear.getSelectedItem().toString(),price.getText(),color.getSelectedItem().toString(),contacts.getText(),grandtot,vint.getText());
                this.setVisible(false);
                obj.setVisible(true);
           
        }   
         catch(SQLException se)
            {
                    se.printStackTrace();
             }
            catch(Exception e)
            {
                e.printStackTrace();
            } 
        
        }
    }//GEN-LAST:event_booknowMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        frontpage objecte=new frontpage();
        if(brand_ser.getSelectedItem().toString().equals("Select...")||model_ser.getSelectedItem().toString().equals("Select...")||
                gear_ser.getSelectedItem().toString().equals("Select...")||colors.getSelectedItem().toString().equals("Select..."))
        {
            JOptionPane.showMessageDialog(this,"Enter Valid Data...!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
                stmt=con.createStatement();
                String nameee=name_ser.getText();
                String brandee=brand_ser.getSelectedItem().toString();
                String modelse=model_ser.getSelectedItem().toString();
                String gearee=gear_ser.getSelectedItem().toString();
                String priceee=cost_ser.getText();
                String contactee=con_ser.getText();
                String coloree=colors.getSelectedItem().toString();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/ddHH:mm:ss");
                Date dte=new Date();
                String de=dateFormat.format(dte);
                String invoicee = de.replaceAll("[-+.^:,/]","");
                int grandtote=((Integer.parseInt(cost_ser.getText())*13)/100+Integer.parseInt(cost_ser.getText()));
                String se="insert into bill values('"+invoicee+"','"+nameee+"','"+brandee+"','"+modelse+"','"+gearee+"','"+priceee+"','"+contactee+"','"+grandtote+"','"+coloree+"')";
                stmt.executeUpdate(se);
                System.out.println("Records inserted into the table...!!!");
                bill obje=new bill(invoicee,name_ser.getText(),brand_ser.getSelectedItem().toString(),model_ser.getSelectedItem().toString(),gear_ser.getSelectedItem().toString(),cost_ser.getText(),colors.getSelectedItem().toString(),con_ser.getText(),grandtote,vint.getText());
                this.setVisible(false);
                obje.setVisible(true);
           
        }   
         catch(SQLException se)
            {
                    se.printStackTrace();
             }
            catch(Exception e)
            {
                e.printStackTrace();
            } 
    }//GEN-LAST:event_payMouseClicked
}
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:this.setcon.c
        try
        {
            con_logout ob=new con_logout(con);
            this.setVisible(false);
            ob.setVisible(true);
        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }  
    }//GEN-LAST:event_logoutMouseClicked

    private void getdetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getdetailMouseClicked
        // TODO add your handling code here:
        try
        {
             stmt=con.createStatement();
             String sq="select * from bill where invoicenumber='"+search_invoice.getText()+"'";
             ResultSet rs=stmt.executeQuery(sq);
             if(rs.next())
             {
                 System.out.println("Record Found");
                 
                 String name_user=rs.getString("name");
                 String brand_user=rs.getString("brand");
                 String model_user=rs.getString("model");
                 String gear_user=rs.getString("gear");
                 String price_user=rs.getString("price");
                 String contact_user=rs.getString("contact");
                 String grandtotal_user=rs.getString("grandtotal");
                 String color_user=rs.getString("color");
                 
                 userdetail ab=new userdetail(name_user,brand_user,model_user,contact_user,grandtotal_user);
                 this.setVisible(false);
                 ab.setVisible(true);
                 
                 
             }
           else
            {
                JOptionPane.showMessageDialog(this,"No Such Record found!!!","Error",JOptionPane.ERROR_MESSAGE);
            }   
        }catch(Exception e)
        {
            e.printStackTrace();
        }
            
       
    }//GEN-LAST:event_getdetailMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        try{
            //stmt = con.createStatement();
            String search=search_emp.getText();
            String sq="SELECT name,empid,contact,grade,address FROM employee_car where empid='"+search+"'";
              //String sq="insert into blood values('"+nam+"','"+sx+"','"+bloodg+"','"+ph+"')";
                  float num1;
                    try 
                    {
                        stmt=con.createStatement();
                        ResultSet rs = stmt.executeQuery(sq);
                        if(rs.next())
                        {
                                    System.out.println("Record Found");
                                    String name  = rs.getString("name");
                                    String empid = rs.getString("empid");
                                    String contact_emp = rs.getString("contact");
                                    String grade = rs.getString("grade");
                                    String address_emp=rs.getString("address");
                                    employeedetail obj=new employeedetail(name,empid,contact_emp,grade,address_emp);
                                    obj.setVisible(true);
                                    this.setVisible(false);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"No Such Record found!!!","Error",JOptionPane.ERROR_MESSAGE);
                        }
                                  
                    } 
                    catch (NumberFormatException e) 
                    {
                        JOptionPane.showMessageDialog(this, "Please enter numbers only", "Error!!!", JOptionPane.ERROR_MESSAGE);
                    }
        }
        catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }
    }//GEN-LAST:event_searchMouseClicked

    private void colorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorsActionPerformed

    private void totsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totsaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totsaleActionPerformed

    private void tot_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tot_saleMouseClicked
        // TODO add your handling code here:
        try
        {
            int sum=0;
            String ts="select sum(grandtotal) from bill";
            stmt=con.createStatement();
            ResultSet res = stmt.executeQuery(ts);
            while (res.next()) 
            {
              int c = res.getInt(1);
              sum = sum + c;
            }
            String val=Integer.toString(sum);
            totsale.setText(val);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_tot_saleMouseClicked

    private void convertibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertibleActionPerformed

    private void convert_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convert_saleMouseClicked
        // TODO add your handling code here:
        try
        {
            //4--5
            int[] maximum = new int[13];
            for(int i=0;i<=12;i++)
            {
                maximum[i]=0;
            }
            String md="Convertible";
            String s="select invoicenumber from bill where model='"+md+"'";
             stmt=con.createStatement();
             ResultSet rst = stmt.executeQuery(s);
             //System.out.println("manaaj");
            if(rst.next())
            {
                      
                        //System.out.println(Integer.parseInt(val.substring(4,5)));
                        String val=rst.getString("invoicenumber");
                          String su=val.substring(4, Math.min(6, val.length()));
                          int v=Integer.parseInt(su);
                         // System.out.println("month: "+Integer.parseInt(su));
                          maximum[v]=maximum[v]+1;
                        /*for(int i=0;i<13;i++)
                        {
                            System.out.println(maximum[i]);
                        }*/
                        int ms=-1,ig=-1;
                        for(int i=0;i<13;i++)
                        {
                            if(ms<=maximum[i])
                            {
                                ms=maximum[i];
                                ig=i;
                            }
                        }
                    switch(ig)
                    {
                        case 0:
                            JOptionPane.showMessageDialog(this,"No such month exist!!!","Error",JOptionPane.INFORMATION_MESSAGE);
                            break;
                            case 1:
                                convertible.setText("JANUARY");
                            break;
                            case 2:
                                convertible.setText("FEBURARY");
                            break;
                            case 3:
                                convertible.setText("MARCH");
                            break;
                            case 4:
                                convertible.setText("APRIL");

                            break;
                            case 5:
                                                        convertible.setText("MAY");

                            break;
                            case 6:
                                                        convertible.setText("JUNE");

                            break;
                            case 7:
                                                        convertible.setText("JULY");

                            break;
                            case 8:
                                                        convertible.setText("AUGUST");

                            break;
                            case 9:
                                                        convertible.setText("SEPTEMBER");

                            break;
                            case 10:
                                                        convertible.setText("OCTOBER");

                            break; 
                            case 11:
                                                        convertible.setText("NOVEMBER");

                            break;
                            case 12:
                                                        convertible.setText("DECEMBER");

                            break;
                    }
        }
            else
            {
                JOptionPane.showMessageDialog(this,"No Car sold!!!","Error",JOptionPane.INFORMATION_MESSAGE);
            }
             
         }
        
        catch(SQLException e)
        {
            e.printStackTrace();
            
        }
        
    }//GEN-LAST:event_convert_saleMouseClicked

    private void top_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_salesMouseClicked
        // TODO add your handling code here:
        top_sale q=new top_sale();
        this.setVisible(false);
        q.setVisible(true);
        
    }//GEN-LAST:event_top_salesMouseClicked

    private void vintbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vintbuttonMouseClicked
        // TODO add your handling code here:
        
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/ddHH:mm:ss");
                Date dte=new Date();
                String de=dateFormat.format(dte);
                String inv = de.replaceAll("[-+.^:,/]","");
               
                if(model.getSelectedItem().toString().equals("Select..."))
                {
                    JOptionPane.showMessageDialog(this,"Select the Car Model First","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    inv=inv+model.getSelectedItem().toString();
                    vint.setText(inv);
                    String p=Integer.toString(hm.get(model.getSelectedItem().toString()));
                    price.setText(p);
                    
                    
                }
                
    }//GEN-LAST:event_vintbuttonMouseClicked

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void brand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand1ActionPerformed

    private void booknow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booknow1MouseClicked
        // TODO add your handling code here:
        
        frontpage object=new frontpage();
        if(brand1.getSelectedItem().toString().equals("Select...")||model1.getSelectedItem().toString().equals("Select...")||
                gear1.getSelectedItem().toString().equals("Select...")||color1.getSelectedItem().toString().equals("Select...")||no_car.getSelectedItem().toString().equals("Select..."))
        {
            JOptionPane.showMessageDialog(this,"Enter Valid Data...!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
            
                stmt=con.createStatement();
                String namee=name1.getText();
                String brande=brand1.getSelectedItem().toString();
                String models=model1.getSelectedItem().toString();
                String geare=gear1.getSelectedItem().toString();
                String pricee=price1.getText();
                String colore=color1.getSelectedItem().toString();
                String contact=contacts1.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/ddHH:mm:ss");
                Date dt=new Date();
                String d=dateFormat.format(dt);
                String invoice = d.replaceAll("[-+.^:,/]","");
                //String set="M"+invoice;
                // vint.setText(set);
                int grandtot=((Integer.parseInt(price1.getText())*13)/100+Integer.parseInt(price1.getText()))*Integer.parseInt(no_car.getSelectedItem().toString());
               // String s="insert into bill values('"+invoice+"','"+namee+"','"+brande+"','"+models+"','"+geare+"','"+pricee+"','"+contacte+"','"+grandtot+"','"+colore+"','"+sex+"','"+salary+"')";
                //stmt.executeUpdate(s);
                pricee=Integer.toString(grandtot);
                String str="insert into manufracturer values('"+namee+"','"+brande+"','"+models+"','"+geare+"','"+colore+"','"+no_car.getSelectedItem().toString()+"','"+vint1.getText()+"','"+contact+"','"+pricee+"')";
                stmt.executeUpdate(str);
                System.out.println("Records inserted into the table...!!!");
                bill obj=new bill(invoice,name1.getText(),brand1.getSelectedItem().toString(),model1.getSelectedItem().toString(),gear1.getSelectedItem().toString(),price1.getText(),color1.getSelectedItem().toString(),contacts1.getText(),grandtot,vint1.getText());
                this.setVisible(false);
                obj.setVisible(true);
           
        }   
         catch(SQLException se)
            {
                    se.printStackTrace();
             }
            catch(Exception e)
            {
                e.printStackTrace();
            } 
        
        }
        
        
    }//GEN-LAST:event_booknow1MouseClicked

    private void vintbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vintbutton1MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/ddHH:mm:ss");
                Date dte=new Date();
                String de=dateFormat.format(dte);
                String inv = de.replaceAll("[-+.^:,/]","");
               
                if(model1.getSelectedItem().toString().equals("Select..."))
                {
                    JOptionPane.showMessageDialog(this,"Select the Car Model First","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    //(Integer.parseInt(price1.getText())*13)/100+Integer.parseInt(price1.getText())
                    inv=inv+model1.getSelectedItem().toString();
                    vint1.setText(inv);
                    String t=hm.get(model1.getSelectedItem()).toString();
                    String p=Integer.toString(hm.get(model1.getSelectedItem().toString()));
                    int v=Integer.parseInt(t)*(Integer.parseInt(no_car.getSelectedItem().toString()));
                    price1.setText(Integer.toString(v));
                }
        
    }//GEN-LAST:event_vintbutton1MouseClicked

    private void contacts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacts1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacts1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton booknow;
    private javax.swing.JToggleButton booknow1;
    private javax.swing.JComboBox<String> brand;
    private javax.swing.JComboBox<String> brand1;
    private javax.swing.JComboBox<String> brand_ser;
    private javax.swing.JComboBox<String> color;
    private javax.swing.JComboBox<String> color1;
    private javax.swing.JComboBox<String> colors;
    private javax.swing.JTextField con_ser;
    private javax.swing.JLabel contact_ser;
    private javax.swing.JTextField contacts;
    private javax.swing.JTextField contacts1;
    private javax.swing.JToggleButton convert_sale;
    private javax.swing.JTextField convertible;
    private javax.swing.JTextField cost_ser;
    private javax.swing.JComboBox<String> gear;
    private javax.swing.JComboBox<String> gear1;
    private javax.swing.JComboBox<String> gear_ser;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JToggleButton getdetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton logout;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JComboBox<String> model1;
    private javax.swing.JComboBox<String> model_ser;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name_ser;
    private javax.swing.JComboBox<String> no_car;
    private javax.swing.JToggleButton pay;
    private javax.swing.JTextField price;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField salary;
    private javax.swing.JToggleButton search;
    private javax.swing.JTextField search_emp;
    private javax.swing.JTextField search_invoice;
    private javax.swing.JTable tab;
    private javax.swing.JToggleButton top_sales;
    private javax.swing.JToggleButton tot_sale;
    private javax.swing.JTextField totsale;
    private javax.swing.JLabel vin;
    private javax.swing.JLabel vin1;
    private javax.swing.JTextField vint;
    private javax.swing.JTextField vint1;
    private javax.swing.JToggleButton vintbutton;
    private javax.swing.JToggleButton vintbutton1;
    // End of variables declaration//GEN-END:variables
}
