/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aman_car_showroom;

import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Aman Kumar Jha
 */
public class top_sale extends javax.swing.JFrame {

    /**
     * Creates new form top_sale
     */
    Connection connt=null;
    Statement stmtt=null;
    ResultSet rss=null;
    PreparedStatement ps=null;

    public top_sale() {
        String url="url:oracle:thin:@localhost:1521:XE";
        try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                System.out.println("Driver loaded\n");
                connt=DriverManager.getConnection(url,"system","aman");
            }
            catch(ClassNotFoundException e)
            {
                System.out.println("driver not found\n");
            }
            catch(SQLException e)
            {
                System.out.println("Connection not establish");
            }
            if(connt!=null)
            {
                System.out.println("Connection Established\n");
                
               initComponents();
              
               
               //fetch();
            }   
      // initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        selectmodel = new javax.swing.JLabel();
        getsales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        higestsales = new javax.swing.JToggleButton();
        numberofcar = new javax.swing.JTextField();
        totalrevenue = new javax.swing.JTextField();
        goback = new javax.swing.JToggleButton();
        carmodels = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JToggleButton();
        saletrend = new javax.swing.JLabel();
        female = new javax.swing.JToggleButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMAN ENTERPRISE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 490, 34));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "HatchBack-S-Class", "HatchBack-E-Class", "HatchBack-A-Class", "Sedan-E-Class", "MPV-S-Class", "SUV-E-Class", "SUV-A-Class", "Crossover", "Coupe", "Convertible" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 220, 30));

        selectmodel.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        selectmodel.setText("SELECT MODEL:");
        getContentPane().add(selectmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, 30));

        getsales.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        getsales.setText("GET SALES");
        getsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getsalesMouseClicked(evt);
            }
        });
        getContentPane().add(getsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel2.setText("__________________________________________________________________________________________________________________");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 680, 20));

        jLabel3.setText("____________________________________________________________________________________________________________________");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 720, 30));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel5.setText("NUMBER OF CAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("TOTAL REVENUE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 30));

        higestsales.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        higestsales.setText("HIGHEST SALE");
        higestsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                higestsalesMouseClicked(evt);
            }
        });
        getContentPane().add(higestsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 30));

        numberofcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofcarActionPerformed(evt);
            }
        });
        getContentPane().add(numberofcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 220, 30));
        getContentPane().add(totalrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 220, 30));

        goback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        goback.setText("<<");
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 20, 90, 30));

        carmodels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carmodelsActionPerformed(evt);
            }
        });
        getContentPane().add(carmodels, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("CAR MODEL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 30));

        male.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        male.setText("MALE");
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 110, 30));

        saletrend.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        saletrend.setText("GET SALES TRENDS:");
        getContentPane().add(saletrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 30));

        female.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        female.setText("FEMALE");
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberofcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofcarActionPerformed

    private void carmodelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carmodelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carmodelsActionPerformed

    private void higestsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_higestsalesMouseClicked
        // TODO add your handling code here:
        try
        {
            int []sale=new int[10];
            int []cnt=new int[10];
            String []carmodel=new String[10];
            carmodel[0]="HatchBack-S-Class";
            carmodel[1]="HatchBack-E-Class";
            carmodel[2]="HatchBack-A-Class";
            carmodel[3]="Sedan-E-Class";
            carmodel[4]="MPV-S-Class";
            carmodel[5]="SUV-E-Class";
            carmodel[6]="SUV-A-Class";
            carmodel[7]="Crossover";
            carmodel[8]="Coupe";
            carmodel[9]="Convertible";
           
            for(int i=0;i<10;i++)
            {
                //select sum(grandtotal) from bill
                int sum=0,times=0;
                String mdl=carmodel[i];
                //System.out.println(mdl);
                String qu="select grandtotal from bill where model='"+mdl+"'";
                stmtt=connt.createStatement();
                ResultSet rss = stmtt.executeQuery(qu);
                if(rss.next())
                {
                    while (rss.next()) 
                    {
                      int c = rss.getInt("grandtotal");
                      sum = sum + c;
                      times++;
                    }
                    String val=Integer.toString(sum);
                    sale[i]=sale[i]+Integer.parseInt(val);
                    cnt[i]=times;
                }
            }
            /*for(int i=0;i<10;i++)
            {
                System.out.println(sale[i]);
            }*/
            int maxs=-1,pos=-1;
            for(int i=0;i<10;i++)
            {
                if(maxs<sale[i])
                {
                    maxs=sale[i];
                    pos=i;
                }
            }
            System.out.println(carmodel[pos]);
            System.out.println(Integer.toString(cnt[pos]));
            System.out.println(Integer.toString(maxs));
           carmodels.setText((carmodel[pos]));
            numberofcar.setText(Integer.toString(cnt[pos]));
            totalrevenue.setText(Integer.toString(maxs));
            
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
            
    }//GEN-LAST:event_higestsalesMouseClicked

    private void getsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getsalesMouseClicked
        // TODO add your handling code here:
        try
        {
            String s=jComboBox1.getSelectedItem().toString();
            String qwe="select * from bill where model='"+s+"'";
            stmtt=connt.createStatement();
            int t=0,c=0;
                ResultSet rss = stmtt.executeQuery(qwe);
                if(rss.next())
                {
                    while(rss.next())
                    {
                        t=t+rss.getInt("grandtotal");
                        c++;
                    }
                }
                carmodels.setText(s);
            numberofcar.setText(Integer.toString(c));
            totalrevenue.setText(Integer.toString(t));
                
        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_getsalesMouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        // TODO add your handling code here:frontpage
        frontpage fg=new frontpage();
        this.setVisible(false);
        fg.setVisible(true);
        
    }//GEN-LAST:event_gobackMouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked
        // TODO add your handling code here:
        female_sales obj=new female_sales();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_femaleMouseClicked

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked
        // TODO add your handling code here:
        male_sales obj=new male_sales();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_maleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(top_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(top_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(top_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(top_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new top_sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carmodels;
    private javax.swing.JToggleButton female;
    private javax.swing.JButton getsales;
    private javax.swing.JToggleButton goback;
    private javax.swing.JToggleButton higestsales;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton male;
    private javax.swing.JTextField numberofcar;
    private javax.swing.JLabel saletrend;
    private javax.swing.JLabel selectmodel;
    private javax.swing.JTextField totalrevenue;
    // End of variables declaration//GEN-END:variables
}
