/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aman_car_showroom;

/**
 *
 * @author Aman Kumar Jha
 */
public class userdetail extends javax.swing.JFrame {

    /**
     * Creates new form userdetail
     */
    public userdetail() {
        
    }
    public userdetail(String name_user,String brand_user,String model_user,String contact_user,String grandtotal_user)
    {
        //userdetail on=new userdetail();
        initComponents();
        user_detail_name.setText(name_user);
        user_detail_brand.setText(brand_user);
        user_detail_model.setText(model_user);
        user_detail_contact.setText(contact_user);
        user_detail_amount.setText(grandtotal_user);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gobackuser = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_detail_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        user_detail_contact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user_detail_brand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user_detail_model = new javax.swing.JTextField();
        user_detail_amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gobackuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gobackuser.setText("<<");
        gobackuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackuserMouseClicked(evt);
            }
        });
        getContentPane().add(gobackuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMAN ENTERPRISE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 490, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel2.setText("NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 30));
        getContentPane().add(user_detail_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel3.setText("CONTACT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));
        getContentPane().add(user_detail_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 230, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setText("BRAND:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));
        getContentPane().add(user_detail_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 230, 30));

        jLabel5.setText("________________________________________________________________________________________________________________");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 670, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel6.setText("AMOUNT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel7.setText("MODEL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));
        getContentPane().add(user_detail_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 230, 30));
        getContentPane().add(user_detail_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 230, 30));

        jLabel8.setText("_______________________________________________________________________________________________________________");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackuserMouseClicked
        // TODO add your handling code here:
        frontpage f=new frontpage();
        this.setVisible(false);
        f.setVisible(true);
        
    }//GEN-LAST:event_gobackuserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new userdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton gobackuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField user_detail_amount;
    private javax.swing.JTextField user_detail_brand;
    private javax.swing.JTextField user_detail_contact;
    private javax.swing.JTextField user_detail_model;
    private javax.swing.JTextField user_detail_name;
    // End of variables declaration//GEN-END:variables
}
